### ISSUE TITLE
Cannot convert to a class with numbers as member names

### ISSUE THREAD

**Issue by filharvey** [edjCase/ICP.NET#10]
I have a call which returns this candid.

`"([{0:\'content\'; 1:qaa6y-5yaaa-aaaaa-aaafa-cai}, {0:\'global\'; 1:qhbym-qaaaa-aaaaa-aaafq-cai}])"`

But you cannot have a C# class which is like this

`public class services_canister
{
            public string 0;
            public string 1; 
}`

**Comment by Gekctek** [comment]
Now is fixed with [CandidName()] attribute to override the name. the client now generates property names that are safe
