### ISSUE TITLE
It Seems you need Create PathSegmentCborConverter for PathSegment

### ISSUE THREAD

**Issue by godcare** [edjCase/ICP.NET#4]
When Send ReadStatus Returned Failed: Could not parse body as read request: invalid type: map, expected a borrowed byte array
So I Create a class below:

public class PathSegmentCborConverter : CborConverterBase<PathSegment?>
    {
        public override PathSegment? Read(ref CborReader reader)
        {
            throw new System.NotImplementedException();
        }
        public override void Write(ref CborWriter writer, PathSegment? value)
        {
            if (value == null)
            {
                writer.WriteNull();
                return;
            }
            writer.WriteByteString(value.Value);
        }
    }

**Comment by Gekctek** [comment]
Thanks. Pushed a change with this in it
