### ISSUE TITLE
Add a flag in the code generator to always use the candid name instead of an alias.

### ISSUE THREAD

**Issue by LorenzGit** [edjCase/ICP.NET#41]
Please add a flag on the Code Generator so that you can always use the same names as represented on Candid and avoid using the attribute [CandidName].

**Comment by Gekctek** [comment]
Im just going to have it not include by default. I might add a flag later, but only if requested

Fixed in #44

**Comment by LorenzGit** [comment]
Can we add a configuration flag so that the names are never changed? for example if candid says a field is named "id" it will be named "id" also in C#.
