### ISSUE TITLE
Generate simple enums when a full object variant is not necessary

### ISSUE THREAD

**Issue by LorenzGit** [edjCase/ICP.NET#43]
Currently any enum is generated as a variant object in C#, which makes sense for enums that have structs with extra values inside. Although, could it be possible for the generator to understand when an enum is simple in certain cases? essentially not generating it as a variant, but just as a simple enum?

So that:
variant { #one; #two; #three }

would generate
enum A { one, two, three }

Instead of a class + enum

The main reason is performance. In most cases, when you want an enum to act simply as their pure form of constant integral identifiers, if you have a list of many objects, it is faster to use them as enums instead of having to create a new object for each one of them.

**Comment by Gekctek** [comment]
Fixed in #44
