### ISSUE TITLE
EdjCase.Cryptography.BLS not found on nuget

### ISSUE THREAD

**Issue by kentsday** [edjCase/ICP.NET#49]
https://www.nuget.org/packages/EdjCase.Cryptography.BLS/

**Comment by Gekctek** [comment]
Ya, currently it's sitting in limbo waiting on a crypto expert to help me figure out what isn't working.

**Comment by Gekctek** [comment]
Is this causing an error right now? I guess I didn't consider that. Maybe i can upload a dummy one

**Comment by Gekctek** [comment]
@kentsday 
Alright. Try 2.0.7
https://www.nuget.org/packages/EdjCase.Cryptography.BLS/2.0.7

**Comment by kentsday** [comment]
thx, it works!
