### ISSUE TITLE
Issue Generating c# files for icrc1_ledger ckbtc 

### ISSUE THREAD

**Issue by ItsJackAnton** [edjCase/ICP.NET#78]
I updated the c# generator to the latest (3.1.2) I tried to generate the c# files for icrc1_ledger ckbtc using its canister id . There is a bug when generating its files, The "Candid.Icrc1Ledger.Models.Value" is the only one being affected. The Value field's name is identical to the class name and t
image 1: https://github.com/edjCase/ICP.NET/assets/44788655/da79f864-c95c-4bff-a9fa-06bfe070900f
image 2: https://github.com/edjCase/ICP.NET/assets/44788655/c3630538-7730-417c-bcac-5d2f8285bc2f

**Comment by Gekctek** [comment]
https://github.com/edjCase/ICP.NET/releases/tag/3.1.3
